# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [18]:
import numpy as np

In [19]:
arr= np.random.randint(0, 20, size = (4, 7))
arr_min = np.min(arr)
arr_max = np.max(arr)
(arr-arr_min)/(arr_max-arr_min)


array([[1.        , 0.57894737, 0.63157895, 0.57894737, 0.78947368,
        0.94736842, 0.26315789],
       [0.84210526, 0.21052632, 0.73684211, 0.68421053, 0.26315789,
        0.21052632, 0.        ],
       [0.68421053, 0.84210526, 0.73684211, 0.10526316, 0.36842105,
        0.10526316, 0.89473684],
       [0.36842105, 0.21052632, 0.47368421, 0.21052632, 1.        ,
        0.36842105, 0.94736842]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [20]:
arr2 = np.random.uniform(0, 10, (8,10))
arr2_argmin = np.argmin(np.sum(arr2, axis=1))
arr2[arr2_argmin]

array([6.46927805, 0.89179299, 6.89623628, 4.07726389, 4.40142141,
       7.65179035, 2.25488272, 4.15561488, 1.46972152, 0.10165131])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [21]:
arr3 = np.random.randint(0, 10, size=10)
print(arr3)
arr4 = np.random.randint(0, 10, size=10)
print(arr4)
np.linalg.norm(arr3 - arr4)

[0 6 8 3 7 4 1 3 2 8]
[9 6 3 3 0 1 9 5 4 3]


16.15549442140351

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [22]:
a = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.matrix([[3, -1], [2, 1]])
c = np.matrix([[7, 21], [11, 8], [8, 4]])
np.linalg.inv(a) @ -c @ np.linalg.inv(b)

matrix([[ 1.00000000e+00,  5.32907052e-16],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [23]:
import numpy as np
with open('minutes_n_ingredients.csv', 'r') as f:
    new_file = f.readlines()[1:]

with open('minutes_n_ingredients.txt', 'w') as file:
    for line in new_file:
        file.write(line)    
    
a=np.loadtxt('minutes_n_ingredients.txt', delimiter=',', dtype=np.int32 )  
a[0:5]

   

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [24]:
a[::,1:].mean(axis=0)


array([2.16010017e+04, 9.05528000e+00])

In [25]:
a[::,1:].min(axis=0)

array([0, 1])

In [26]:
a[::,1:].max(axis=0)

array([2147483647,         39])

In [27]:
np.median(a[::,1:],axis=0)

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [28]:
quar= np.quantile(a[::,1], q=0.75, axis=0)
a[a[::,1]<=quar]




array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [29]:
nul = a[::,1]==0
print(a[nul].shape[0])
a_new = a.copy()
a_new[nul, 1] = 1
a_new[nul]

479


array([[9325,    1,   10],
       [2828,    1,    8],
       [8008,    1,   11],
       ...,
       [3383,    1,    7],
       [2778,    1,   11],
       [4747,    1,    9]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [30]:
np.unique(a, axis=1).shape[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [46]:
np.unique(a[::,2]).shape[0]

37

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [45]:
a[a[::,2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [43]:
a_new[::,2]/a_new[:,1]

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [44]:
np.max(a_new[::,2]/a_new[:,1])

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [35]:
np.sum(a[a[::, 1].argsort()][::-1][:100,2])/100

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [36]:
a[np.random.randint(a.shape[0], size=10)]

array([[303231,     25,      6],
       [304507,    105,     11],
       [112912,     20,      9],
       [197285,     70,     13],
       [  9298,     20,      3],
       [136171,     40,      4],
       [167894,     26,      8],
       [445613,     45,      9],
       [534266,     75,      6],
       [ 48122,     75,     11]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [37]:
a[a[::,2] < a[::,2].mean()].shape[0]/a.shape[0]*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [42]:
a2 = np.c_[a, (a[::,1] <= 20) * (a[:,2]<=5)]
a2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [41]:
a2[a2[::,3]!=0].shape[0]/a2.shape[0]*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [40]:
short = a[a[::, 2] < 10]
stand = a[(a[::, 2] >= 10) * (a[::,2] < 20)]
long = a[a[::, 2] >= 20]
max_len = min(short.shape[0], stand.shape[0], long.shape[0])
a3 = np.array([short[:max_len], stand[:max_len], long[:max_len]])
a3

array([[[ 23891,     25,      7],
        [ 94746,     10,      6],
        [ 67660,      5,      6],
        ...,
        [230210,     30,      6],
        [281614,     25,      8],
        [139843,     50,      6]],

       [[127244,     60,     16],
        [157911,     60,     14],
        [280968,     85,     11],
        ...,
        [382527,     55,     12],
        [ 19716,     30,     10],
        [ 37210,     25,     10]],

       [[504666,     65,     20],
        [ 44512,     50,     20],
        [470973,    180,     20],
        ...,
        [188457,    735,     26],
        [ 51720,     30,     22],
        [451245,    390,     21]]])